[project]
name = "spoc-shot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hf-transfer>=0.1.9",
    "huggingface-hub>=0.33.0",
    "vllm>=0.9.1",
]
